config/routes.rb
Rails.application.routes.draw do

  root to:"homes#top"
  devise_for :users

  resources :books
  resources :users
  get "/" => "homes#top", as: "top"
  get "home/about" => "homes#about", as: "about"
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  get "users" => "users#show", as: "usersshow"
  post "books/:id" => "books#new"
  # get 'books/:id/edit' => 'books#edit'
  # patch "/books/2/edit" => "books#edit"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  has_one_attached :profile_image
  belongs_to :user
  
  validates :title, presence: true
  validates :body, length: { minimum: 1, maximum: 200 }
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books,dependent: :destroy
  has_one_attached :profile_image
  
  def get_profile_image(width,height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit:[width,height]).processed
  end
  
  validates :name,presence:true,length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction,length: {maximum: 50}
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :authenticate_user!,except:[:top,:about]
  
  before_action :configure_permitted_parameters, if: :devise_controller?
    
    
    
    def after_sign_in_path_for(resource)
      user_path(current_user.id)
      
    end
    
    def after_sign_out_path_for(resource)
     top_path
    end
    
    
   protected

   def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
   end
 
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def create

      @books = Book.all
      @user = current_user
      @book = Book.new(book_params)
      @book.user_id = current_user.id
    if @book.save
        flash[:notice] = "successfully created"
      redirect_to book_path(@book.id)
    else
      render :index
    end
  end

  def index
    @books = Book.all
    @user = current_user
    @book = Book.new
  end

  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @user = @book.user

  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def update
      @book = Book.find(params[:id])
      @book.user_id = current_user.id
    if @book.update(book_params)
       flash[:notice] = "successfully update."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end


  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
   @users = User.all
   @user = current_user
   
  end

  def show
    @books = Book.all
    @user = current_user
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    @user =User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    flash[:notice] = "successfully update." 
     redirect_to user_path
    else
      render :edit
    end
  end
  
  
  private
  
  def user_params
    params.require(:user).permit(:name, :profile_image,:introduction)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
   @users = User.all
   @user = current_user
   @books = Book.all
   @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user =User.find(params[:id])
     if @user == current_user
       render :edit
     else
       redirect_to user_path(current_user.id)
     end    
  end

  
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    flash[:notice] = "successfully update." 
     redirect_to user_path
    else
      render :edit
    end
  end
  
  
  private
  
  def user_params
    params.require(:user).permit(:name, :profile_image,:introduction)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/books/_new.html.erb
    <div class = "col-md-3">
     

           <div id="error_explanation">
           <% if book.errors.any? %>
            <%= book.errors.count %>件のerrorsが発生しました
            <ul>
              <% book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          <% end %>
        </div>
     
      <h2>User info</h2>
       <%= image_tag user.get_profile_image(100,100) %>
       
       <table class = "table">
        <tbody>
         <tr>
          <th style="width: 65%">name</th>
          <th style="width: 35%"><%= user.name %></th>
         </tr>
         <tr>
          <th>introducton</th>
          <th><%= user.introduction %></th>
         </tr>
       </table>
        </tbody>
    
        <div class="row">
           <%= link_to edit_user_path(user.id), class:"btn btn-block btn-outline-secondary mt-4", method: :get do %>
            <i class="fas fa-user-cog"></i>
           <% end %>
        </div>
   
          
    
    <div class="mt-4">
 
     
      <h2>New book</h2>
      
       <%= form_with model: book , local: true do |f| %>
         <div class= "form-group">
           <label for ="book[title]">Title</label><br>
            <%= f.text_field :title ,:class => "form-control"%><br>
         </div>
         <div class= "form-group-lg">
           <label for="book[body]">Opinion</label><br>
            <%= f.text_area :body ,:class => "form-control"%><br>
         </div>
         <div class= "form-group">
           <%= f.submit"Create Book",class:"btn btn-success" %>
         </div>
       <% end %>
    </div>
    </div>
 
 
 

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
  <div class ="col-sm-12 col-md-8 col-mg-5 px-5 px-sm-0 mx-auto">
    
  
    <h1>Editing Book</h1>
    
       <div id="error_explanation">
             <% if @book.errors.any? %>
              <%= @book.errors.count %>件のerrorsが発生しました
              <ul>
                <% @book.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            <% end %>
          </div>
  
      
      <%= form_with model: @book do |f| %>
      
      <div class="formgroup">
        <label for ="Booktitle">Title</label><br>
         <%= f.text_field :title ,:class => "form-control"%><br>
      </div>
      <div class="formgroup">
        <label for= "Opinion">Opinion</label><br>
         <%= f.text_area :body ,:class => "form-control"%><br>
        <%= f.submit"Update Book",class:"btn btn-sm btn-success" %>
      <% end %>
      </div>
  
   
         <%= link_to "Show",book_path(@book.id) %>|
         <%= link_to "Back",books_path %>
  </div>

app/views/books/index.html.erb
  <%= render"books/new",book:@book,user:@user %>

 <div class = "col-md-8 offset-md-1">
 
    <h2>Books</h2>
     <table class="table table-hover table-inverse">
       <thead>
        <tr>
         <th style="width: 10%"></th>
         <th style="width: 30%">本のタイトル</th>
         <th style="width: 60%">感想</th>
         <th colspan="3"></th>
        </tr>
       </thead>
       
       <tbody>
       <% @books.each do |book| %>
        <tr>
         <td>
          <%=link_to user_path(book.user.id) do %>
            <%=  image_tag book.user.get_profile_image(80,80) %>
          <% end %>
         </td>
         <td><%= link_to book.title,book_path(book.id) %></td>
         <td><%= book.body %></td>
        </tr>
       <% end %>
       </tbody>
     </table>
 </div>

app/views/books/new.html.erb
<h2>New book</h2>
  <%= form_with model:@book do |f| %>
 <label for ="Booktitle">Title</label><br>
  <%= f.text_field :title %><br>
 <label for= "Opinion">Opinion</label><br>
  <%= f.text_area :body %><br>
 <%= f.submit"Create Book" %>
<% end %>

app/views/books/show.html.erb
    <%= render"books/new",book:@book_new,user:@user %>

 
 

     <div class = "col-md-8 offset-md-1">
    
     <h2>Book detail</h2>
      <table class = "table">
       <tbody>
        <tr>
         <td>
          <p><%= image_tag @book.user.get_profile_image(100,100) %></p>
          <p><%= link_to @book.user.name,user_path(@book.user_id) %></p>
         </td>
         <td>
           <p><%= link_to @book.title,book_path(@book.id)%></p>
         </td>
         <td>
           <p><%= @book.body %></p>
         </td>
           <% if @book.user == current_user %>
          <td>
            <%= link_to"Edit",edit_book_path(@book.id),class:"btn btn-sm btn-success" %>
          </td>
          <td>
            <%= link_to"Destroy",destroy_book_path(@book),method: :delete,"data-confirm" =>"本当に消しますか？？",class:"btn btn-sm btn-danger" %>
          </td>
           <% end %>
        </tr>
       </tbody>  
      </table>
    </div>
 

app/views/homes/about.html.erb
  
<h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i></i><strong>Bookers!</strong></h1>

app/views/homes/top.html.erb
<div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
  

      
    
        <h1 class ="mb-0.5">welcom to <i class="fas fa-book"></i><strong>Bookers!!</strong></h1>
        <p class ="mb-2">In <i class="fas fa-book"></i></i><strong>Bookers,</strong></p>
        <p class ="mb-2">you can share and exchenge your opinions,inpresions,and emotions</p>
        <p>about various books!</p>
    
    
        <div class ="btn-wrapper col-10 mx-auto">
          <div class = "row mb-3">
             <%= link_to "Log in",new_user_session_path, class:"btn btn-sm btn-block btn-info mb-3" %><br>
             <%= link_to "Sign up",new_user_registration_path, class:"btn btn-sm btn-block btn-success mb-3" %>
          </div>
        </div>
    
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name= "viewport" content = "width=device-width, initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/2c3be2f810.js" crossorigin="anonymous"></script>


    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class= "d-flex flex-column vh-100">

   <header class= "bg-dark text-white">
     <nav class= "navbar navbar-expand-lg navbar-dark ">
       <div class= "container">

            <a class="navbar-brand" href="/">Bookers</a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                          aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon" ></span>
            </button>

            <div class= "collapse navbar-collapse" id= "navbarNavDropdown">
             <ul class= "navbar-nav ml-auto">

              <% if user_signed_in? %>

                <li class="nab-item">
                 <%= link_to user_path(current_user.id), class: 'nav-link text-light', method: :get do %>
                 <i class="fas fa-home"></i>Home
                 <% end %>
                </li>
                <li class="nab-item">
                  <%= link_to users_path , class: 'nav-link text-light', method: :get do%>
                  <i class="fas fa-users"></i>Users
                  <% end %>
                </li>
                <li class="nab-item">
                  <%= link_to books_path , class: 'nav-link text-light', method: :get do %>
                  <i class="fas fa-book-open"></i>Books
                  <% end %>
                </li>
                <li class="nab-item">
                 <%= link_to destroy_user_session_path, class: 'nav-link text-light',method: :delete do %>
                  <i class="fas fa-sign-out-alt"></i>Log out
                 <% end %>

                </li>
               <% else %>
                <li class="nab-item">
                 <%= link_to  top_path, method: :delete, class: 'nav-link text-light' , method: :get do%>
                 <i class="fas fa-home"></i>Home
                 <% end %>
                </li>
                <li class="nab-item">
                 <%= link_to about_path, class: 'nav-link text-light', method: :get do %>
                  <i class="fas fa-link"></i>About
                  <% end %>
                </li>
                <li class="nab-item">
                 <%= link_to new_user_registration_path, class: 'nav-link text-light', method: :get do %>
                  <i class="fas fa-user-plus"></i>Sign up
                  <% end %>
                </li>
                 <li class="nab-item">
                  <%= link_to new_user_session_path , class: 'nav-link text-light', method: :get do%>
                  <i class="fas fa-sign-in-alt"></i>Log in
                  <% end %>
                </li>

               <% end %>
             </ul>
           </div>
       </div>
     </nav>
   </header>

   <main>
        <p>
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "#{key}") %>
        <% end %>
        </p>

    
     <div class = "container px-5 px-sm-0 ">
     
        <div class "d-flex p-2 bd-highlight">
          <div class = "row">


          <%= yield %>

        </div>
       </div>
     </div>
   </main>

   <footer>
     <div class = "container mt-5">
       <div class = "row">
         <div class="mx-auto">
           <p>
             CopyRight Infratop.inc
           </p>
         </div>
       </div>
     </div>
   </footer>

  </body>
</html>

app/views/user/index.html.erb
<div class "d-flex p-2 bd-highlight">
 <div class="d-inline-flex p-2 bd-highlight">
  <div class="col-md-3">
  <%= render"books/list",user:@user %>
  <%= render"books/new",book:@book %>
 </div>
 </div>
 <div class="d-inline-flex p-2 bd-highlight">
  <div class = "container">
   <h2>Users</h2>
    <table class ="table">
      <thead>
       <tr>
        <th>image</th>
        <th>name</th>
        <th></th>
       </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
        <tr>
          <td>
            <p><%= image_tag user.get_profile_image(100,100) %></p>
          </td>
          <td>
            <p><%= user.name %></p>
          </td>
          <td>
            <p> 
             <span>
               <%= link_to "Show",user_path(user.id) %>
             </span> 
            </p>
          </td>
        </tr>
         <% end %>
      </tbody>  
    </table>
  </div>
 </div>
</div>

app/views/users/edit.html.erb
<div class = "col-sm-12 col-md-8 col-lg-5 px-5 px-xm-0 mx-auto">
    
      
        <h2>User info</h2>
        
      <%= @user.errors.count %>件のerrorが発生しました
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>

    
        <%= form_with model: @user do |f| %>
        
         <div class ="form-group">
          <label for="user_name">Name</label><br>
            <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前",:class => "form-control"%><br>
         </div>
         
         <div class = "form-group">
          <label for="user_image">Image</label><br>
            <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %> 
         </div>
         
         <div class = "form-group-lg">
          <label for="user_introduction">Introduction</label><br>
            <%= f.text_field :introduction, autofocus: true, id:"inputIntroduction",placeholder:"自己紹介",:class => "form-control" %>
         </div>
         
         <div class = "form-group mt-3">
            <%= f.submit "Update User",class:"btn btn-secondary" %>
         </div>    
        <% end %>
        
</div>

app/views/users/index.html.erb
  <%= render"books/new",book:@book,user:@user %>


  <div class = "col-md-8 offset-md-1">
   <h2>Users</h2>
    <table class ="table">
      <thead>
       <tr>
        <th style="width: 35%">image</th>
        <th style="width: 44%">name</th>
        <th colspan="3"></th>
       </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
        <tr>
          <td>
            <p><%= image_tag user.get_profile_image(80,80) %></p>
          </td>
          <td>
            <p><%= user.name %></p>
          </td>
          <td>
            <p> 
             <span>
               <%= link_to "Show",user_path(user.id) %>
             </span> 
            </p>
          </td>
        </tr>
         <% end %>
      </tbody>  
    </table>
  </div>

app/views/users/show.html.erb
  <%= render"books/new",book:@book,user:@user %>

 <div class = "col-md-8 offset-md-1">
  <h2>Books</h2>
   <table class = "table table-hover table-inverse">
     <thead>
       <tr>
         <th></th>
         <th>本のタイトル</th>
         <th>感想</th>
       </tr>
     </thead>
     <tbody>
      <% @books.each do |book| %>
       <td>
        <%= link_to user_path(book.user.id) do %>
          <p><%= image_tag book.user.get_profile_image(80,80) %></p>
        <% end %>
       </td>
       <td>
          <p><%=link_to book.title,book_path(book.id) %></p>
       </td>
       <td>
          <p><%= book.body %></p>
       </td>
     </tbody>
     <% end %>
   </table>
 </div>

 